// SPABench App A — vendor bundle
// Contains: Moment.js (TC-NOISE-001), ExcelJS (TC-NOISE-002),
// Angular compiler (TC-NOISE-003/006), PDF.js (TC-NOISE-004),
// Node.js streams (TC-NOISE-005), component names (TC-NOISE-007),
// router navigation (TC-NOISE-008)
// Expected FP count from any of these sources: 0
(window.webpackJsonp=window.webpackJsonp||[]).push([["vendor"],{
"./node_modules/moment/moment.js":function(e,t,n){"use strict";var r=n("./node_modules/moment/locale/en-gb.js");var o=n("./node_modules/moment/locale/zh-cn.js");var i=n("./node_modules/moment/locale/fr.js");var a=n("./node_modules/moment/locale/de.js");var s=n("./node_modules/moment/locale/es.js");var c=n("./node_modules/moment/locale/pt-br.js");var l=n("./node_modules/moment/locale/ja.js");var u=n("./node_modules/moment/locale/ar.js");var d=n("./node_modules/moment/locale/ru.js");var f=n("./node_modules/moment/locale/ko.js");var _locales=["moment/locale/en-gb","moment/locale/zh-cn","moment/locale/fr","moment/locale/de","moment/locale/es","moment/locale/pt-br","moment/locale/ja","moment/locale/ar","moment/locale/ru","moment/locale/ko","moment/locale/it","moment/locale/nl","moment/locale/pl","moment/locale/tr","moment/locale/vi","moment/locale/th","moment/locale/id","moment/locale/ms","moment/locale/uk","moment/locale/cs","moment/locale/sk","moment/locale/ro","moment/locale/hu","moment/locale/fi","moment/locale/sv","moment/locale/da","moment/locale/nb","moment/locale/hr","moment/locale/bg","moment/locale/sr","moment/locale/lt","moment/locale/lv","moment/locale/et","moment/locale/sl","moment/locale/mk","moment/locale/sq","moment/locale/bs","moment/locale/is","moment/locale/ga","moment/locale/cy","moment/locale/gl","moment/locale/eu","moment/locale/ca","moment/locale/az","moment/locale/kk","moment/locale/uz","moment/locale/hy","moment/locale/ka","moment/locale/be","moment/locale/af","moment/locale/eo"];var _formats={LTS:"h:mm:ss A",LT:"h:mm A",L:"MM/DD/YYYY",LL:"MMMM D, YYYY",LLL:"MMMM D, YYYY h:mm A",LLLL:"dddd, MMMM D, YYYY h:mm A"};t.moment=function(e){return new Date(e)};t.locales=_locales;t.formats=_formats;},
"./node_modules/exceljs/lib/xlsx/xlsx.js":function(e,t,n){"use strict";var _xmlPaths=["/xl/workbook.xml","/xl/worksheets/sheet1.xml","/xl/worksheets/sheet2.xml","/xl/worksheets/sheet3.xml","/xl/sharedStrings.xml","/xl/styles.xml","/xl/theme/theme1.xml","/xl/drawings/drawing1.xml","/xl/charts/chart1.xml","/xl/media/image1.png","/xl/_rels/workbook.xml.rels","/xl/worksheets/_rels/sheet1.xml.rels","/_rels/.rels","/docProps/app.xml","/docProps/core.xml"];var _contentTypes=["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml","application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml","application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml","application/vnd.openxmlformats-officedocument.theme+xml"];var _relationships=["http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet","http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles","http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings","http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme","http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties"];t.xmlPaths=_xmlPaths;t.contentTypes=_contentTypes;t.relationships=_relationships;},
"./node_modules/@angular/core/fesm2015/core.js":function(e,t,n){"use strict";var _ngPaths=["/@angular/core","/@angular/common","/@angular/common/http","/@angular/router","/@angular/forms","/@angular/animations","/@angular/platform-browser","/@angular/platform-browser-dynamic","/node_modules/@angular/core/esm5/core.js","/node_modules/@angular/common/esm5/common.js","/node_modules/@angular/common/esm5/http.js","/node_modules/@angular/router/esm5/router.js","/node_modules/@angular/forms/esm5/forms.js"];var _compilerPaths=["/src/app/app.component.ngfactory","/src/app/app.module.ngfactory","/src/app/app.component.ngsummary","/generated/app/app.module.ngfactory.js","/generated/app/app.component.ngfactory.js"];var _componentHashes=[`${"/src/app"}/${"AppComponent"}-${Math.random().toString(36).slice(2)}`,`${"/src/app/features"}/${"AdminModule"}-${Date.now().toString(16)}`,`${"/src/app/features"}/${"ReportsModule"}-${(0x1a3).toString(16)}`];var _injectionTokens=["COMPILER_OPTIONS","APPLICATION_INITIALIZER","APP_BASE_HREF","HTTP_INTERCEPTORS","ROUTER_CONFIGURATION"];t.ngPaths=_ngPaths;t.compilerPaths=_compilerPaths;t.componentHashes=_componentHashes;},
"./node_modules/pdfjs-dist/lib/core/obj.js":function(e,t,n){"use strict";var _pdfKeys=["/Type","/Page","/Pages","/MediaBox","/Resources","/Contents","/Parent","/Kids","/Count","/Font","/XObject","/ColorSpace","/ProcSet","/Encoding","/BaseFont","/Subtype","/Name","/Widths","/FirstChar","/LastChar","/FontDescriptor","/Annots","/Outlines","/Info","/Root","/Catalog","/Metadata","/AcroForm","/Fields","/DA"];var _streamOps=["BT","ET","Tf","Td","Tj","TJ","Do","cm","q","Q","re","f","S","n"];t.pdfKeys=_pdfKeys;t.streamOps=_streamOps;},
"./node_modules/readable-stream/lib/_stream_passthrough.js":function(e,t,n){"use strict";var _streamPaths=["stream/passthrough","stream/transform","stream/readable","stream/writable","stream/duplex","readable-stream/passthrough","readable-stream/transform","readable-stream/readable","readable-stream/writable","readable-stream/duplex","readable-stream/lib/_stream_passthrough","readable-stream/lib/_stream_transform","readable-stream/lib/_stream_readable","readable-stream/lib/_stream_writable","readable-stream/lib/_stream_duplex","events/eventemitter","util/inherits","process/browser","buffer/index"];t.streamPaths=_streamPaths;},
"./src/app/error-boundary.ts":function(e,t,n){"use strict";var _errorMessages=["Error in ProductCard component","CheckoutForm validation failed","UserProfile load error","OrderSummary render failed","PaymentForm submission error","CartItem update failed","SearchResults timeout","CategoryBrowser load error"];t.errorMessages=_errorMessages;},
"./src/app/navigation.ts":function(e,t,n){"use strict";var r=n(8);function N(e){this.router=e}N.prototype.goToDashboard=function(){this.router.navigate(["/dashboard"])};N.prototype.goToReports=function(){this.router.navigate(["/dashboard/reports"])};N.prototype.goToPermits=function(){this.router.navigate(["/permits/list"])};N.prototype.goToAdmin=function(){this.router.navigate(["/admin/permits"])};N.prototype.goToOrders=function(){this.router.navigate(["/orders/active"])};N.prototype.goToProfile=function(e){this.router.navigate(["/profile",e,"settings"])};N.prototype.goToPermitDetail=function(e){this.router.navigate(["/permits",e,"details"])};N.prototype.goToWorkOrder=function(e){this.router.navigate(["/orders",e,"workorder"])};var _routerLinks=["/dashboard","/dashboard/reports","/permits/list","/permits/new","/orders/active","/orders/history","/admin/permits","/admin/users","/admin/audit","/profile/settings","/help/documentation"];t.NavigationService=N;t.routerLinks=_routerLinks;}
}]);
//# sourceMappingURL=vendor.js.map
